name: ebbot_flutter_ui_example
description: Example application demonstrating the usage of ebbot_flutter_ui library.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.2.6"

dependencies:
  flutter:
    sdk: flutter
  
  # Use the library from parent directory
  ebbot_flutter_ui:
    path: ../

  # UI dependencies for chat
  flutter_chat_ui: ^1.6.12
  
  # Environment variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true